#!/bin/bash

#Start Picom Compostitor

picom &

# Start Spotifyd Service

# spotifyd

#Set Display Resolution

xrandr --output DisplayPort-2 --primary --mode 3840 × 2160
xrandr --output Display-Port-2 --right-of --output eDP
# Set Wallpaper

feh --bg-fill ~/.config/bspwm/new1.jpg

# Launch Polybar

$HOME/.config/polybar/launch.sh

# BSPWM Config
####################### 
xsetroot -cursor_name left_ptr
sxhkd &
 
bspc config split_ratio		0.62
bspc config focus_follows_pointer	true
bspc config pointer_modifier	mod1
# WM Scheme
bspc config automatic_scheme	spiral
 
bspc rule -a Chromium desktop='^2'
bspc rule -a Gimp desktop='^8' state=floating follow=onr

# Window Gaps
gap=15
PANEL_HEIGHT=25
export gap
export PANEL_HEIGHT

#This creates negative padding equal to window gap so that gaps are shown only between windows and not on desktop edges.

bspc config top_padding $(($PANEL_HEIGHT-$gap))
bspc config border_width            3
bspc config window_gap              12
bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config paddingless_monocle     true
bspc config click_to_focus          true
bspc config focused_border_color    '#03629b'
